# Generated by Django 4.2.5 on 2023-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
