# Generated by Django 4.2.5 on 2023-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needs_approval',
            field=models.BooleanField(default=True),
        ),
    ]
