# Generated by Django 4.2.5 on 2023-11-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_project_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
        migrations.AddField(
            model_name='repository',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repositories', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='repository',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_repositories', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='repository_files/'),
        ),
        migrations.AddField(
            model_name='repository',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='repository_images/'),
        ),
    ]
