# Generated by Django 4.2.5 on 2023-11-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_repository_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='is_approved',
        ),
    ]
