# Generated by Django 4.2.5 on 2023-11-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_repository_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='created_by',
        ),
    ]
