# Generated by Django 4.2.5 on 2023-11-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_repository_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='upload_image',
        ),
    ]
