# Generated by Django 4.2.5 on 2023-11-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_repository_full_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='full_file_path',
        ),
    ]
