# Generated by Django 4.2.5 on 2023-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_repository_full_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_file_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
