# Generated by Django 4.2.5 on 2023-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_repository_full_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
