# Generated by Django 4.2.5 on 2023-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_assign_to_task_name_remove_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('completed', 'Completed'), ('incompleted', 'Incomplete')], max_length=20),
        ),
    ]
