# Generated by Django 4.2.5 on 2023-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_task_completed_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('completed', 'Completed'), ('incompleted', 'Incomplete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
