# Generated by Django 4.2.5 on 2023-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('completed', 'Completed'), ('incompleted', 'Incomplete')], default='incompleted', max_length=20),
        ),
    ]
