# Generated by Django 4.2.5 on 2023-11-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_repositories', to='myapp.userprofile'),
        ),
    ]
