# Generated by Django 4.2.5 on 2023-11-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_repository_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='created_by',
        ),
    ]
