# Generated by Django 4.2.5 on 2023-11-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_feedback_name_feedback_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback', to='myapp.userprofile'),
        ),
    ]
