# Generated by Django 4.2.5 on 2023-11-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_feedback_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_by',
        ),
    ]
