# Generated by Django 4.2.5 on 2023-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_feedback_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
