# Generated by Django 4.2.5 on 2023-11-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='role',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_collaborator', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
