# Generated by Django 4.2.5 on 2023-11-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_collaborator_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
